INSERT INTO PostContent (post_id, content_type, text_content, media_url) VALUES
                                                                             (1,  'text', 'just deployed my first spring boot app. only cried twice.',                        NULL),
                                                                             (2,  'text', 'hot take: postgresql is the best database and its not even close',                  NULL),
                                                                             (3,  'text', 'summited camelback at sunrise. almost passed out but the views were worth it',      NULL),
                                                                             (4,  'text', 'woke up at 5am voluntarily. who even am i anymore',                                NULL),
                                                                             (5,  'text', 'its 3am and i just discovered my entire codebase has a typo in every variable name. shipping it anyway.', NULL),
                                                                             (6,  'text', 'should i learn rust or go next? wrong answers only',                               NULL),
                                                                             (7,  'text', 'golden hour in sedona. no filter needed when the sky does this',                    NULL),
                                                                             (8,  'text', 'my dog learned to open the fridge. we are in the endgame now.',                     NULL),
                                                                             (9,  'text', 'euler identity is proof that math is just poetry with extra steps',                 NULL),
                                                                             (10, 'text', 'made homemade pasta for the first time. life will never be the same',               NULL),
                                                                             (11, 'text', 'redesigned my portfolio for the 47th time. this is the one. (it is not the one.)', NULL),
                                                                             (12, 'text', 'new pr on deadlift today. the grind never stops',                                  NULL),
                                                                             (13, 'text', 'only twice? thats actually impressive for spring boot',                             NULL),
                                                                             (14, 'text', 'welcome to the club. the errors only get weirder from here',                        NULL),
                                                                             (15, 'text', 'what stack? i need to know everything',                                             NULL),
                                                                             (16, 'text', 'how early did you start?? i can barely make it to 9am lectures',                   NULL),
                                                                             (17, 'text', 'the desert sunrise hits different. need to go back',                                NULL),
                                                                             (18, 'text', 'postgresql supremacy. this is the way.',                                            NULL),
                                                                             (19, 'text', 'this is either genius or unhinged. respect either way',                             NULL),
                                                                             (20, 'text', 'rust. always rust. the borrow checker builds character',                            NULL),
                                                                             (21, 'text', 'go is way easier to pick up honestly. rust is a time commitment',                   NULL),
                                                                             (22, 'text', 'sedona is unreal. how do you even capture that light??',                            NULL),
                                                                             (23, 'text', 'euler identity walked so complex analysis could run',                               NULL),
                                                                             (24, 'text', 'have you read "a mathematicians apology"? youd love it',                            NULL),
                                                                             (25, 'text', 'ok recipe or it didnt happen',                                                      NULL),
                                                                             (26, 'text', 'what program are you running? been looking for a new split',                        NULL);